const SUCCESS_ACTION = 'SUCCESS_ACTION';
const ERROR_ACTION = 'ERROR_ACTION';
const CLEAR_ACTION = 'CLEAR_ACTION';

const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const REGISTER = 'REGISTER';

const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';

const REGISTER_REQUEST = 'REGISTER_REQUEST';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_ERROR = 'REGISTER_ERROR';

const FAVORITE = 'favorite';
const LIKE = 'like';

const GET_GAMES = 'GET_GAMES';
const GET_GAMES_REQUEST = 'GET_GAMES_REQUEST';
const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
const GET_GAMES_ERROR = 'GET_GAMES_ERROR';

const GET_GAME_BY_USER_ID = 'GET_GAME_BY_USER_ID';
const GET_GAME_BY_USER_ID_REQUEST = 'GET_GAME_BY_USER_ID_REQUEST';
const GET_GAME_BY_USER_ID_SUCCESS = 'GET_GAME_BY_USER_ID_SUCCESS';
const GET_GAME_BY_USER_ID_ERROR = 'GET_GAME_BY_USER_ID_ERROR';

const INIT_GAME = 'INIT_GAME';
const START_GAME = 'START_GAME';
const START_GAME_REQUEST = 'START_GAME_REQUEST';
const START_GAME_SUCCESS = 'START_GAME_SUCCESS';
const START_GAME_CANCELED = 'START_GAME_CANCELED';
const START_GAME_ERROR = 'START_GAME_ERROR';

const RESTART_GAME = 'RESTART_GAME';
const RESTART_GAME_REQUEST = 'RESTART_GAME_REQUEST';
const RESTART_GAME_SUCCESS = 'RESTART_GAME_SUCCESS';
const RESTART_GAME_CANCELED = 'RESTART_GAME_CANCELED';
const RESTART_GAME_ERROR = 'RESTART_GAME_ERROR';

const FINISH_GAME = 'FINISH_GAME';
const FINISH_GAME_SUCCESS = 'FINISH_GAME_SUCCESS';
const FINISH_GAME_ERROR = 'FINISH_GAME_ERROR';

const SAVE_GAME = 'SAVE_GAME';
const SAVE_GAME_SUCCESS = 'SAVE_GAME_SUCCESS';
const SAVE_GAME_ERROR = 'SAVE_GAME_ERROR';

const GET_GAMES_PROPS = 'GET_GAMES_PROPS';
const GET_GAMES_PROPS_REQUEST = 'GET_GAMES_PROPS_REQUEST';
const GET_GAMES_PROPS_SUCCESS = 'GET_GAMES_PROPS_SUCCESS';
const GET_GAMES_PROPS_ERROR = 'GET_GAMES_PROPS_FAILURE';

const UPDATE_GAME_PROP = 'UPDATE_GAME_PROP';
const UPDATE_GAME_PROP_SUCCESS = 'UPDATE_GAME_PROP_ERROR';
const UPDATE_GAME_PROP_ERROR = 'UPDATE_GAME_PROP_ERROR';

const GAME_ACTION = 'GAME_ACTION';
const GAME_ACTION_REQUEST = 'GAME_ACTION_REQUEST';
const GAME_ACTION_RESPONSE = 'GAME_ACTION_RESPONSE';
const GAME_ACTION_ERROR = 'GAME_ACTION_ERROR';

const CHANGE_SETTINGS = 'CHANGE_SETTINGS';
const CHANGE_SETTINGS_RESPONSE = 'CHANGE_SETTINGS_RESPONSE';
const CHANGE_SETTINGS_ERROR = 'CHANGE_SETTINGS_ERROR';

export default {
  SUCCESS_ACTION,
  ERROR_ACTION,
  CLEAR_ACTION,

  LOGIN,
  REGISTER,
  LOGOUT,

  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_ERROR,

  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_ERROR,

  FAVORITE,
  LIKE,

  GET_GAMES,
  GET_GAMES_REQUEST,
  GET_GAMES_SUCCESS,
  GET_GAMES_ERROR,

  GET_GAME_BY_USER_ID,
  GET_GAME_BY_USER_ID_REQUEST,
  GET_GAME_BY_USER_ID_SUCCESS,
  GET_GAME_BY_USER_ID_ERROR,

  INIT_GAME,
  START_GAME,
  START_GAME_REQUEST,
  START_GAME_SUCCESS,
  START_GAME_CANCELED,
  START_GAME_ERROR,

  RESTART_GAME,
  RESTART_GAME_REQUEST,
  RESTART_GAME_SUCCESS,
  RESTART_GAME_CANCELED,
  RESTART_GAME_ERROR,

  FINISH_GAME,
  FINISH_GAME_SUCCESS,
  FINISH_GAME_ERROR,

  SAVE_GAME,
  SAVE_GAME_SUCCESS,
  SAVE_GAME_ERROR,

  GAME_ACTION,
  GAME_ACTION_REQUEST,
  GAME_ACTION_RESPONSE,
  GAME_ACTION_ERROR,

  GET_GAMES_PROPS,
  GET_GAMES_PROPS_REQUEST,
  GET_GAMES_PROPS_SUCCESS,
  GET_GAMES_PROPS_ERROR,

  UPDATE_GAME_PROP,
  UPDATE_GAME_PROP_SUCCESS,
  UPDATE_GAME_PROP_ERROR,

  CHANGE_SETTINGS,
  CHANGE_SETTINGS_RESPONSE,
  CHANGE_SETTINGS_ERROR,
};
