const SUCCESS_ACTION = 'SUCCESS_ACTION';
const ERROR_ACTION = 'ERROR_ACTION';
const CLEAR_ACTION = 'CLEAR_ACTION';

const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const REGISTER = 'REGISTER';

const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';

const REGISTER_REQUEST = 'REGISTER_REQUEST';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_ERROR = 'REGISTER_ERROR';

const FAVORITE = 'favorite';
const LIKE = 'like';

const GET_GAMES = 'GET_GAMES';
const GET_GAMES_REQUEST = 'GET_GAMES_REQUEST';
const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
const GET_GAMES_ERROR = 'GET_GAMES_ERROR';

const GET_GAMES_PROPS = 'GET_GAMES_PROPS';
const GET_GAMES_PROPS_SUCCESS = 'GET_GAMES_PROPS_SUCCESS';
const GET_GAMES_PROPS_ERROR = 'GET_GAMES_PROPS_FAILURE';

const UPDATE_GAME_PROP = 'UPDATE_GAME_PROP';
const UPDATE_GAME_PROP_SUCCESS = 'UPDATE_GAME_PROP_ERROR';
const UPDATE_GAME_PROP_ERROR = 'UPDATE_GAME_PROP_ERROR';

export default {
  SUCCESS_ACTION,
  ERROR_ACTION,
  CLEAR_ACTION,

  LOGIN,
  REGISTER,
  LOGOUT,

  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_ERROR,

  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_ERROR,

  FAVORITE,
  LIKE,

  GET_GAMES,
  GET_GAMES_REQUEST,
  GET_GAMES_SUCCESS,
  GET_GAMES_ERROR,

  GET_GAMES_PROPS,
  GET_GAMES_PROPS_SUCCESS,
  GET_GAMES_PROPS_ERROR,

  UPDATE_GAME_PROP,
  UPDATE_GAME_PROP_SUCCESS,
  UPDATE_GAME_PROP_ERROR,
};
