const SUCCESS = 'SUCCESS';
const ERROR = 'ERROR';
const CLEAR = 'CLEAR';

const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGOUT = 'LOGOUT';

const REGISTER_REQUEST = 'REGISTER_REQUEST';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAILURE = 'REGISTER_FAILURE';

const GET_ALL_GAMES_REQUEST = 'GET_ALL_GAMES_REQUEST';
const GET_ALL_GAMES_SUCCESS = 'GET_ALL_GAMES_SUCCESS';
const GET_ALL_GAMES_FAILURE = 'GET_ALL_GAMES_FAILURE';
const UPDATE_GAME_TYPE = 'UPDATE_GAME_TYPE';

const FAVORITE = 'favorite';
const LIKE = 'like';

export default {
  SUCCESS,
  ERROR,
  CLEAR,

  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT,

  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,

  GET_ALL_GAMES_REQUEST,
  GET_ALL_GAMES_SUCCESS,
  GET_ALL_GAMES_FAILURE,
  UPDATE_GAME_TYPE,

  FAVORITE,
  LIKE,
};
